{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-jam.fullname" . }}-postgres
  labels:
    {{- include "open-jam.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
  selector:
    {{- include "open-jam.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
