// <auto-generated />
using System;
using EmailService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmailService.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604155231_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmailService.Data.Entities.EmailConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_key");

                    b.HasKey("Id")
                        .HasName("pk_email_configs");

                    b.HasIndex("TemplateKey")
                        .IsUnique()
                        .HasDatabaseName("ix_email_configs_template_key");

                    b.ToTable("email_configs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "帳號開通驗證信",
                            TemplateKey = "email.verification"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "密碼重置信",
                            TemplateKey = "email.password_reset"
                        });
                });

            modelBuilder.Entity("EmailService.Data.Entities.EmailConfigTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_html");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmailConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("email_config_id");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_email_config_translations");

                    b.HasIndex("EmailConfigId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_email_config_translations_email_config_id_locale");

                    b.ToTable("email_config_translations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyHtml = "<p>感謝您註冊 Open Jam！</p>\n<p>請點擊以下連結驗證您的電子信箱：</p>\n<p><a href=\"{{VerifyUrl}}\" style=\"display:inline-block;padding:10px 20px;background:#6d28d9;color:#fff;text-decoration:none;border-radius:4px;\">驗證帳號</a></p>\n<p style=\"color:#6b7280;font-size:14px;\">連結將在 {{ExpiresInHours}} 小時後失效。若非您本人操作，請忽略此信。</p>",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmailConfigId = 1,
                            Locale = "zh-TW",
                            Subject = "Open Jam 帳號驗證"
                        },
                        new
                        {
                            Id = 2,
                            BodyHtml = "<p>我們收到了您的密碼重置請求。</p>\n<p>請點擊以下連結重置您的密碼：</p>\n<p><a href=\"{{ResetUrl}}\" style=\"display:inline-block;padding:10px 20px;background:#6d28d9;color:#fff;text-decoration:none;border-radius:4px;\">重置密碼</a></p>\n<p style=\"color:#6b7280;font-size:14px;\">連結將在 {{ExpiresInHours}} 小時後失效。若非您本人操作，請忽略此信。</p>",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmailConfigId = 2,
                            Locale = "zh-TW",
                            Subject = "Open Jam 密碼重置"
                        });
                });

            modelBuilder.Entity("EmailService.Data.Entities.EmailRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_html");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("to");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_email_records");

                    b.HasIndex("OutboxMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_email_records_outbox_message_id");

                    b.ToTable("email_records", (string)null);
                });

            modelBuilder.Entity("EmailService.Data.Entities.EmailConfigTranslation", b =>
                {
                    b.HasOne("EmailService.Data.Entities.EmailConfig", "EmailConfig")
                        .WithMany("Translations")
                        .HasForeignKey("EmailConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_config_translations_email_configs_email_config_id");

                    b.Navigation("EmailConfig");
                });

            modelBuilder.Entity("EmailService.Data.Entities.EmailConfig", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
