{{- if .Values.mailpit.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-jam.fullname" . }}-mailpit
  labels:
    {{- include "open-jam.labels" . | nindent 4 }}
    app.kubernetes.io/component: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "open-jam.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mailpit
  template:
    metadata:
      labels:
        {{- include "open-jam.labels" . | nindent 8 }}
        app.kubernetes.io/component: mailpit
    spec:
      containers:
        - name: mailpit
          image: {{ .Values.mailpit.image }}
          ports:
            - containerPort: 1025
              name: smtp
            - containerPort: 8025
              name: ui
          readinessProbe:
            httpGet:
              path: /
              port: ui
            initialDelaySeconds: 5
            periodSeconds: 5
{{- end }}
