CREATE DATABASE open_jam_auth;
CREATE DATABASE open_jam_log;
CREATE DATABASE open_jam_email;
CREATE DATABASE open_jam_hydra;
CREATE DATABASE open_jam_storage;
CREATE DATABASE open_jam_store;
CREATE DATABASE open_jam_payment;
CREATE DATABASE open_jam_order;
CREATE DATABASE open_jam_content;
