{{- if .Values.docs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-jam.fullname" . }}-docs
  labels:
    {{- include "open-jam.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
spec:
  replicas: {{ .Values.docs.replicaCount }}
  selector:
    matchLabels:
      {{- include "open-jam.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: docs
  template:
    metadata:
      labels:
        {{- include "open-jam.labels" . | nindent 8 }}
        app.kubernetes.io/component: docs
    spec:
      containers:
        - name: docs
          image: {{ printf "%s:%s" .Values.docs.image.repository .Values.docs.image.tag | quote }}
          imagePullPolicy: {{ .Values.docs.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          {{- with .Values.docs.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
{{- end }}
