{{- if .Values.portalWeb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-jam.fullname" . }}-portal-web
  labels:
    {{- include "open-jam.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal-web
spec:
  replicas: {{ .Values.portalWeb.replicaCount }}
  selector:
    matchLabels:
      {{- include "open-jam.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: portal-web
  template:
    metadata:
      labels:
        {{- include "open-jam.labels" . | nindent 8 }}
        app.kubernetes.io/component: portal-web
    spec:
      containers:
        - name: portal-web
          image: {{ printf "%s:%s" .Values.portalWeb.image.repository .Values.portalWeb.image.tag | quote }}
          imagePullPolicy: {{ .Values.portalWeb.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          env:
            - name: WORKSPACE_PAGE_URL
              value: {{ .Values.config.workspaceUrl | quote }}
            - name: CREATOR_PAGE_BASE_URL
              value: {{ .Values.config.creatorBaseUrl | quote }}
            - name: OIDC_AUTHORITY
              value: {{ include "open-jam.hydraPublicUrl" . | quote }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.config.oidcClientId | quote }}
            - name: AUTH_PAGE_URL
              value: {{ .Values.config.authPageUrl | quote }}
            - name: GITHUB_REPO_URL
              value: {{ .Values.config.githubRepoUrl | quote }}
            - name: DOCS_URL
              value: {{ .Values.config.docsUrl | quote }}
            - name: CATALOG_API_URL
              value: {{ .Values.config.catalogApiUrl | quote }}
            - name: STORE_API_URL
              value: {{ .Values.config.storeApiUrl | quote }}
          {{- with .Values.portalWeb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
{{- end }}
