{{- if and .Values.hydra.enabled .Values.hydra.migrateJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "open-jam.fullname" . }}-hydra-migrate
  labels:
    {{- include "open-jam.labels" . | nindent 4 }}
    app.kubernetes.io/component: hydra-migrate
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: {{ .Values.hydra.migrateJob.ttlSecondsAfterFinished }}
  backoffLimit: {{ .Values.hydra.migrateJob.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "open-jam.labels" . | nindent 8 }}
        app.kubernetes.io/component: hydra-migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: hydra-migrate
          image: {{ .Values.hydra.image }}
          args: ["migrate", "sql", "-e", "--yes"]
          env:
            - name: DSN
              value: {{ printf "postgres://%s:%s@%s:5432/%s_hydra" .Values.postgres.user .Values.secrets.postgres.password (include "open-jam.postgresHost" .) .Values.dbNamePrefix | quote }}
{{- end }}
