{{- if .Values.workspaceWeb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-jam.fullname" . }}-workspace-web
  labels:
    {{- include "open-jam.labels" . | nindent 4 }}
    app.kubernetes.io/component: workspace-web
spec:
  replicas: {{ .Values.workspaceWeb.replicaCount }}
  selector:
    matchLabels:
      {{- include "open-jam.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: workspace-web
  template:
    metadata:
      labels:
        {{- include "open-jam.labels" . | nindent 8 }}
        app.kubernetes.io/component: workspace-web
    spec:
      containers:
        - name: workspace-web
          image: {{ printf "%s:%s" .Values.workspaceWeb.image.repository .Values.workspaceWeb.image.tag | quote }}
          imagePullPolicy: {{ .Values.workspaceWeb.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          env:
            - name: WORKSPACE_PAGE_URL
              value: {{ .Values.config.workspaceUrl | quote }}
            - name: MARKET_PAGE_URL
              value: {{ .Values.config.marketPageUrl | quote }}
            - name: OIDC_AUTHORITY
              value: {{ include "open-jam.hydraPublicUrl" . | quote }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.config.oidcClientId | quote }}
            - name: AUTH_PAGE_URL
              value: {{ .Values.config.authPageUrl | quote }}
            - name: AUTH_API_URL
              value: {{ .Values.config.authApiUrl | quote }}
            - name: STORE_API_URL
              value: {{ .Values.config.storeApiUrl | quote }}
            - name: CATALOG_API_URL
              value: {{ .Values.config.catalogApiUrl | quote }}
            - name: LOG_API_URL
              value: {{ .Values.config.logApiUrl | quote }}
            - name: CONTENT_API_URL
              value: {{ .Values.config.contentApiUrl | quote }}
          {{- with .Values.workspaceWeb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
{{- end }}
