{{- if .Values.creatorWeb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-jam.fullname" . }}-creator-web
  labels:
    {{- include "open-jam.labels" . | nindent 4 }}
    app.kubernetes.io/component: creator-web
spec:
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    {{- include "open-jam.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: creator-web
{{- end }}
