{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-jam.fullname" . }}-auth
  labels:
    {{- include "open-jam.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080": "{{ include "open-jam.fullname" . }}-auth"}}'
spec:
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    {{- include "open-jam.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth
{{- end }}
