{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-jam.fullname" . }}-rabbitmq
  labels:
    {{- include "open-jam.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  clusterIP: None
  ports:
    - port: 5672
      targetPort: amqp
      name: amqp
    - port: 15672
      targetPort: management
      name: management
  selector:
    {{- include "open-jam.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
{{- end }}
