// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuotaService.Data;

#nullable disable

namespace QuotaService.Data.Migrations
{
    [DbContext(typeof(QuotaDbContext))]
    [Migration("20260622133437_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuotaService.Data.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_reservations_product_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_reservations_tenant_id");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_reservations_status_expires_at");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("QuotaService.Data.Entities.TenantUsage", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ProductCount")
                        .HasColumnType("integer")
                        .HasColumnName("product_count");

                    b.Property<long>("Quota")
                        .HasColumnType("bigint")
                        .HasColumnName("quota");

                    b.Property<long>("Reserved")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Used")
                        .HasColumnType("bigint")
                        .HasColumnName("used");

                    b.HasKey("TenantId")
                        .HasName("pk_tenant_usages");

                    b.ToTable("tenant_usages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
