apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-jam.fullname" . }}-wait-for-it
  labels:
    {{- include "open-jam.labels" . | nindent 4 }}
data:
  wait-for-it.sh: |-
{{ .Files.Get "files/wait-for-it.sh" | indent 4 }}
