server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    access_log off;
    error_log /dev/stderr warn;

    location ~* \.(gif|jpg|png|css|js)$ {
        root /usr/share/nginx/html;
    }

    location / {
        sub_filter '</head>'
            '<meta name="HYDRA_PUBLIC_URL" content="${HYDRA_PUBLIC_URL}">
    <meta name="OIDC_CLIENT_ID" content="${OIDC_CLIENT_ID}">
    <meta name="WORKSPACE_URL" content="${WORKSPACE_URL}">
    <meta name="CREATOR_BASE_URL" content="${CREATOR_BASE_URL}">
    </head>';
        sub_filter_once on;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "private, no-cache, no-store, must-revalidate";
        add_header Expires "Sat, 01 Jan 2000 00:00:00 GMT";
        add_header Pragma no-cache;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
