{{- if .Values.storeService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-jam.fullname" . }}-store-service
  labels:
    {{- include "open-jam.labels" . | nindent 4 }}
    app.kubernetes.io/component: store-service
spec:
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    {{- include "open-jam.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: store-service
{{- end }}
